site:
  title: Adaptative Media Player
  start_page: amp-ios::get-started.adoc

runtime:
  fetch: true

content:
  sources: 
  - url: .
    branches: HEAD
    
ui: 
  bundle:
    url: ./antora-ui-default/build/ui-bundle.zip
    snapshot: true
  supplemental_files: './supplemental-ui'